# Generated by Django 4.1.7 on 2023-02-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['title']},
        ),
    ]
