# Generated by Django 4.1.7 on 2023-02-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_rest', '0003_restaurant_lat_restaurant_lon_alter_restaurant_coord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='coord',
        ),
    ]
