# Generated by Django 4.1.7 on 2023-02-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_rest', '0004_remove_restaurant_coord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['title', 'adress']},
        ),
    ]
